check mutual exclusive option + updated readme

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -56,7 +56,24 @@ runs:
             exit 1
           fi
         shell: bash
-      - name: Adding dash (-) to suffix if not null
+      - name: Check only one input set to yes
+        run: |
+          count=0
+          if [[ (${{ inputs.check-only }} == "yes") ]]; then
+            ((count++))
+          fi
+          if [[ (${{ inputs.read-only }} == "yes") ]]; then
+            ((count++))
+          fi
+          if [[ (${{ inputs.release-only }} == "yes") ]]; then
+            ((count++))
+          fi
+          if [ $count -gt 1 ]; then
+            echo "::error:: Only one input can be set to 'yes'"
+            exit 1
+          fi
+        shell: bash
+      - name: Adding dash to suffix
         run: |
           if [[ -n "${{ inputs.suffix }}" ]]; then
             echo "new-suffix=-${{ inputs.suffix }}" >> $GITHUB_ENV
