error if suffix is used with release only

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -55,6 +55,10 @@ runs:
             echo "::error::'${{ inputs.release-only }}' is not a valid input (should be 'yes' or 'no')"
             exit 1
           fi
+          if [[ -n "${{ inputs.suffix }}" ]]; then
+            echo "::error::'suffix' is not allowed with 'release-only' option"
+            exit 1
+          fi
         shell: bash
       - name: Check only one input set to yes
         run: |
