fix semver regex

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -46,8 +46,8 @@ runs:
         shell: bash
       - name: Check version file is valid
         run: |
-          if ! [[ ${{ env.new-version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "::error::'${{ env.new-version }}' is not a valid version format"
+          if ! [[ ${{ env.new-version }} =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
+            echo "::error::'${{ env.new-version }}' is not a valid SemVer version format"
             exit 1
           fi
         shell: bash
